apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-platform.frontend.fullname" . }}

spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.port}}
      targetPort: {{ .Values.frontend.port}}
  selector:
    app: {{ include "fraud-platform.frontend.fullname" . }}