apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "fraud-platform.api.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  ingressClassName: {{ .Values.ingress.className}}

  rules:
    - host: {{ .Values.ingress.host.name}}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "fraud-platform.api.fullname" . }}
                port:
                  number: {{ .Values.api.port}}