apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-platform.api.fullname" . }}-config
data:
  POSTGRES_USER: "fraud"
  POSTGRES_DB: "fraud_db"
  POSTGRES_HOST: {{ include "fraud-platform.db.fullname" . | quote }}
  POSTGRES_PORT: {{ .Values.db.port | quote }}

  RABBITMQ_USER: "guest"
  RABBITMQ_HOST: {{ include "fraud-platform.rabbitmq.fullname" . | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.ports.amqp | quote }}