apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "fraud-platform.api.fullname" . }}-websocket-ingress

spec:
  ingressClassName: {{ .Values.ingress.className}}

  rules:
    - host: {{ .Values.ingress.host.name}}
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "fraud-platform.api.fullname" . }}
                port:
                  number: {{ .Values.api.port}}