apiVersion: v1
kind: Service
metadata:
  name: {{ include "fraud-platform.redis.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - name: {{ include "fraud-platform.redis.fullname" . }}
    port: {{ .Values.redis.port}}
    targetPort: {{ .Values.redis.port}}
  selector:
    app: {{ include "fraud-platform.redis.fullname" . }}