apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-platform.mcp.fullname" . }}-config

data:
  POSTGRES_USER: "fraud"
  POSTGRES_DB: "fraud_db"
  POSTGRES_HOST: {{ include "fraud-platform.db.fullname" . | quote }}
  POSTGRES_PORT: {{ .Values.db.port | quote }}

  REDIS_HOST: {{ include "fraud-platform.redis.fullname" . | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}