apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api_pod
      labels:
        app: api
    spec:
      enableServiceLinks: false
      containers:
      - name: api
        image: fraud-api
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8000
          name: api
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secret