apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fraud-platform.worker.fullname" . }}-config
data:
  POSTGRES_USER: "fraud"
  POSTGRES_DB: "fraud_db"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

  RABBITMQ_USER: "guest"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"