apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mcp
  labels:
    app: mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp
  template:
    metadata:
      name: mcp_pod
      labels:
        app: mcp
    spec:
      enableServiceLinks: false
      containers:
      - name: mcp
        image: gercek-zamanli-e-ticaret-anomali-ve-fraud-tespit-platformu-mcp
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: mcp-config
        - secretRef:
            name: mcp-secret