apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: db 

spec:
  serviceName: db
  replicas: 1 
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: db
        env:
        - name: POSTGRES_USER
          value: "fraud"
        - name: POSTGRES_PASSWORD
          value: "fraud"
        - name: POSTGRES_DB
          value: "fraud_db"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data


  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi 
